pipeline{

    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    // Terraform init
    stages{
        stage('init'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform init
                            terraform fmt
                        """
                    }
                }
            }

        }
        stage('plan'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform plan
                        """
                }
            }
        }
        stage('Apply'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform apply -auto-approve
                        """
                    }
                
                }
            }
        }
        stage('downstream job') {
            steps{
                script{

                   build job: '10-sg',  
                        wait: false
                        propagate: false
                }
            }
        }
    }
        post{
            always{
                echo 'I will always say Hello again!'
                cleanWS()
            }
            success{
                echo 'I will run if success'
            }
            failure{
                echo 'I will run if failing'
            }
            aborted{
                echo 'Pipeline is aborted'
            }
        }
    }
