pipeline{

    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    // Terraform init
    stages{
        stage('init'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform init
                            terraform fmt
                        """
                    }
                }
            }

        }
        stage('plan'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                }
            }
        }
        stage('Deploy'){
            steps{
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                
                }
            }
        }
        stage('parallel trigger') {
            parallel {
                stage('Bastion'){
                    steps {
                        script {
                            build job: '20-bastion',  
                                wait: false,
                                propagate: false
                        }
                }   }
                stage('SG Rules'){
                    steps {
                        script {
                            build job: '30-sg-rules',  
                                wait: false,
                                propagate: false
                        }
                    }
                }
                stage('ACM'){
                    steps {
                        script {
                            build job: '70-acm',  
                                wait: true,
                                propagate: false
                        }
                    }   
                }
                stage('ECR'){
                    steps {
                        script {
                            build job: '40-ecr',  
                                wait: false,
                                propagate: false
                        }
                    }   
                }
                stage('eks'){
                    steps {
                        script {
                            build job: '90-eks',  
                                wait: false,
                                propagate: false
                        }
                    }   
                }
            }   
        }
        stage('ALB'){
            steps {
                script{
                    build job: '80-frontend-alb',
                    wait: false,
                    propagate: false
                }
            }
        }
        }
    }
        post{
            always{
                echo 'I will always say Hello again!'
                cleanWs()
            }
            success{
                echo 'I will run if success'
            }
            failure{
                echo 'I will run if failing'
            }
            aborted{
                echo 'Pipeline is aborted'
            }
        }
    }
