pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 20-bastion
                            terraform init
                            terraform fmt
                        """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 20-bastion
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 20-bastion
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failing'
        }
        aborted {
            echo 'Pipeline is aborted'
        }
    }
}